
GET http://localhost:5000/api/user HTTP/1.1


###

GET http://localhost:5000/api/applications/candidate/632e9ae785aefa5dcde96c84 HTTP/1.1

###

GET http://localhost:5000/api/jobs/ActiveJobs/632dc85905d726428f05f829/all HTTP/1.1



###
PUT http://localhost:5000/api/user/type/632e9ae785aefa5dcde96c84 HTTP/1.1
content-type: application/json

{
    "data": 2 
}

###
POST http://localhost:5000/api/candidates/apply HTTP/1.1
content-type: application/json

{
    "applied_by_user_id": "632e9ae785aefa5dcde96c84",
    "posted_by_user_id": "632dc85905d726428f05f829",
    "job_id": "632ea1f19481c63408149614"
}
###

###
POST http://localhost:5000/api/user HTTP/1.1
content-type: application/json

{
    "firstName": "Muhammad",
    "lastName": "Abrar",
    "email": "ca@a.com",
    "password": "a@a.com"
}
###


GET http://localhost:5000/api/jobs/ HTTP/1.1


###
POST http://localhost:5000/api/jobs HTTP/1.1
content-type: application/json

{
    "title": "New Job Title",
    "industry": "industry name",
    "minimum_age": "16",
    "maximum_age": "44",
    "type": "Full Time",
    "location": "Onsite",
    "priority": "Normal",
    "experience": "1-3 Year",
    "starting_salary": 15000,
    "address": "String",
    "zip_code": "dsad",
    "positions": 4,
    "description": "String",
    "status": 1,
    "user_id": "632dc85905d726428f05f829"
}
###


post http://localhost:5000/api/user/recruiter
content-type: application/json

{
    "userId": "632dc85905d726428f05f829",
    "company": "Omni Softex",
    "about": "IT Company",
    "email": "OmniSoftex@mail.com",
    "CurrentAddress": "I-8, Islamabad",
    "city": "Islamabad",
    "country": "Pakistan",
    "website": "OmniSoftex.com",
    "logo": "",
    "employees": 5
}

###


put http://localhost:5000/api/recruiter
content-type: application/json

{
     "userId": "632dc85905d726428f05f829",
     "company": "Omni Softex",
    "about": "IT Company",
    "email": "OmniSoftex@mail.com",
    "CurrentAddress": "I-8, Islamabad",
    "city": "Islamabad",
    "country": "Pakistan",
    "website": "OmniSoftex.com",
    "logo": "",
    "employees": 5
    
}


